# Generated by Django 4.2.11 on 2024-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_qareports", "0010_auto_20240619_0559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qareportnote",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
